// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClYV-dBQe2ESA3x-lgF5Gni2JHO-4r3Es',
    appId: '1:1076455662458:web:9779bdde12a71084d2ecc3',
    messagingSenderId: '1076455662458',
    projectId: 'zoofeed-a4e73',
    authDomain: 'zoofeed-a4e73.firebaseapp.com',
    storageBucket: 'zoofeed-a4e73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSlN1uOFC34nYMPLQHPWtg9MZWpID1Rsc',
    appId: '1:1076455662458:android:de08b6ab386d5aced2ecc3',
    messagingSenderId: '1076455662458',
    projectId: 'zoofeed-a4e73',
    storageBucket: 'zoofeed-a4e73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyp4axQofudzEfgbTLJsqG7tFckdJgicc',
    appId: '1:1076455662458:ios:f917088ab91d3c2ed2ecc3',
    messagingSenderId: '1076455662458',
    projectId: 'zoofeed-a4e73',
    storageBucket: 'zoofeed-a4e73.firebasestorage.app',
    iosBundleId: 'com.example.zoofeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyp4axQofudzEfgbTLJsqG7tFckdJgicc',
    appId: '1:1076455662458:ios:f917088ab91d3c2ed2ecc3',
    messagingSenderId: '1076455662458',
    projectId: 'zoofeed-a4e73',
    storageBucket: 'zoofeed-a4e73.firebasestorage.app',
    iosBundleId: 'com.example.zoofeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClYV-dBQe2ESA3x-lgF5Gni2JHO-4r3Es',
    appId: '1:1076455662458:web:6334b0b9183d3836d2ecc3',
    messagingSenderId: '1076455662458',
    projectId: 'zoofeed-a4e73',
    authDomain: 'zoofeed-a4e73.firebaseapp.com',
    storageBucket: 'zoofeed-a4e73.firebasestorage.app',
  );
}
