// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkrsqhQZTmHs7-LaUtOA17I81DFxAXVE',
    appId: '1:1092823951598:web:a07a6aadc948e63138ebff',
    messagingSenderId: '1092823951598',
    projectId: 'zoofeed-1a620',
    authDomain: 'zoofeed-1a620.firebaseapp.com',
    storageBucket: 'zoofeed-1a620.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkq7wp4ZMutFFndg4sIOUETAZyIGm63Pg',
    appId: '1:1092823951598:android:925a74dc8d8a60e638ebff',
    messagingSenderId: '1092823951598',
    projectId: 'zoofeed-1a620',
    storageBucket: 'zoofeed-1a620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAECVixFNbkHE1X__V2CWA_vxOXxpVo7HQ',
    appId: '1:1092823951598:ios:efa7acd1073d138838ebff',
    messagingSenderId: '1092823951598',
    projectId: 'zoofeed-1a620',
    storageBucket: 'zoofeed-1a620.firebasestorage.app',
    iosBundleId: 'com.example.zoofeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAECVixFNbkHE1X__V2CWA_vxOXxpVo7HQ',
    appId: '1:1092823951598:ios:efa7acd1073d138838ebff',
    messagingSenderId: '1092823951598',
    projectId: 'zoofeed-1a620',
    storageBucket: 'zoofeed-1a620.firebasestorage.app',
    iosBundleId: 'com.example.zoofeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdkrsqhQZTmHs7-LaUtOA17I81DFxAXVE',
    appId: '1:1092823951598:web:50bbd3774925547f38ebff',
    messagingSenderId: '1092823951598',
    projectId: 'zoofeed-1a620',
    authDomain: 'zoofeed-1a620.firebaseapp.com',
    storageBucket: 'zoofeed-1a620.firebasestorage.app',
  );
}
