import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:provider/provider.dart';
import '../../database/auth_provider.dart' as local_auth;
import '../../models/animal_model.dart';

class TambahBinatangScreen extends StatefulWidget {
  final String zooId;
  final Function(AnimalModel)? onAnimalAdded;

  const TambahBinatangScreen({
    super.key,
    required this.zooId,
    this.onAnimalAdded,
  });

  @override
  State<TambahBinatangScreen> createState() => _TambahBinatangScreenState();
}

class _TambahBinatangScreenState extends State<TambahBinatangScreen> {
  final _formKey = GlobalKey<FormState>();
  final _scaffoldKey = GlobalKey<ScaffoldMessengerState>();

  // Form controllers
  final TextEditingController _namaController = TextEditingController();
  final TextEditingController _speciesController = TextEditingController();
  final TextEditingController _kandangController = TextEditingController();
  final TextEditingController _catatanController = TextEditingController();

  // Form values
  String _selectedJadwal = '2x sehari';
  String _selectedWaktu1 = '08:00';
  String _selectedWaktu2 = '12:00';
  String _selectedWaktu3 = '16:00';
  bool _isActive = true;

  // Loading state
  bool _isLoading = false;

  // Jadwal options
  final List<String> _jadwalOptions = [
    '1x sehari',
    '2x sehari',
    '3x sehari',
    '4x sehari',
    'Custom'
  ];

  // Waktu options
  final List<String> _waktuOptions = [
    '06:00',
    '07:00',
    '08:00',
    '09:00',
    '10:00',
    '11:00',
    '12:00',
    '13:00',
    '14:00',
    '15:00',
    '16:00',
    '17:00',
    '18:00',
    '19:00',
    '20:00'
  ];

  // Spesies suggestions
  final List<String> _spesiesSuggestions = [
    'Singa',
    'Harimau',
    'Gajah',
    'Jerapah',
    'Zebra',
    'Kuda Nil',
    'Buaya',
    'Orangutan',
    'Simpanse',
    'Gorila',
    'Beruang',
    'Serigala',
    'Rubah',
    'Kangguru',
    'Koala',
    'Panda',
    'Flamingo',
    'Burung Hantu',
    'Elang',
    'Ular',
    'Komodo',
    'Kura-kura',
    'Lumba-lumba',
    'Paus',
    'Hiu',
    'Penguin',
  ];

  @override
  void dispose() {
    _namaController.dispose();
    _speciesController.dispose();
    _kandangController.dispose();
    _catatanController.dispose();
    super.dispose();
  }

  Future<void> _tambahBinatang() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() => _isLoading = true);

    try {
      // Generate feeding schedule based on selection
      String feedingSchedule = _selectedJadwal;
      if (_selectedJadwal == 'Custom') {
        final customTimes = [_selectedWaktu1];
        if (_selectedWaktu2.isNotEmpty) customTimes.add(_selectedWaktu2);
        if (_selectedWaktu3.isNotEmpty) customTimes.add(_selectedWaktu3);
        feedingSchedule = customTimes.join(', ');
      }

      // Create animal model
      final animal = AnimalModel(
        id: '', // Will be generated by Firestore
        zooId: widget.zooId,
        name: _namaController.text.trim(),
        species: _speciesController.text.trim(),
        enclosure: _kandangController.text.trim(),
        feedingSchedule: feedingSchedule,
        lastFedDate: null,
        lastFedTime: null,
        fedByUserId: null,
        feedingStatus: 'hungry',
        missedFeedingCount: 0,
        notes: _catatanController.text.trim().isNotEmpty
            ? _catatanController.text.trim()
            : null,
        isActive: _isActive,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // Save to Firestore
      final animalRef = await FirebaseFirestore.instance
          .collection('animals')
          .add(animal.toMap());

      // Update with generated ID
      await animalRef.update({'id': animalRef.id});

      // Show success message
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Binatang berhasil ditambahkan!'),
            backgroundColor: Colors.green,
          ),
        );
      }

      // Call callback if provided
      if (widget.onAnimalAdded != null) {
        final newAnimal = AnimalModel(
          id: animalRef.id,
          zooId: animal.zooId,
          name: animal.name,
          species: animal.species,
          enclosure: animal.enclosure,
          feedingSchedule: animal.feedingSchedule,
          lastFedDate: null,
          lastFedTime: null,
          fedByUserId: null,
          feedingStatus: 'hungry',
          missedFeedingCount: 0,
          notes: animal.notes,
          isActive: animal.isActive,
          createdAt: animal.createdAt,
          updatedAt: animal.updatedAt,
        );
        widget.onAnimalAdded!(newAnimal);
      }

      // Navigate back
      if (mounted) Navigator.pop(context);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Gagal menambahkan binatang: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tambah Binatang Baru'),
        actions: [
          if (_isLoading)
            const Padding(
              padding: EdgeInsets.only(right: 16.0),
              child: Center(
                child: SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              ),
            ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('Informasi Binatang'),
              _buildTextField(
                controller: _namaController,
                label: 'Nama Binatang *',
                hintText: 'Contoh: Simba, Raja, Dumbo',
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Nama binatang harus diisi';
                  }
                  return null;
                },
              ),
              _buildTextField(
                controller: _speciesController,
                label: 'Spesies *',
                hintText: 'Contoh: Singa, Gajah, Harimau',
                suggestions: _spesiesSuggestions,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Spesies harus diisi';
                  }
                  return null;
                },
              ),
              _buildTextField(
                controller: _kandangController,
                label: 'Kandang/Lokasi *',
                hintText: 'Contoh: Kandang A, Area Savana, Akuarium 1',
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Kandang/lokasi harus diisi';
                  }
                  return null;
                },
              ),
              _buildTextField(
                controller: _catatanController,
                label: 'Catatan Khusus',
                hintText: 'Contoh: Alergi makanan tertentu, perilaku khusus',
                maxLines: 3,
              ),
              const SizedBox(height: 24),
              _buildSectionTitle('Jadwal Makan'),
              _buildDropdown(
                value: _selectedJadwal,
                label: 'Frekuensi Makan *',
                items: _jadwalOptions,
                onChanged: (value) {
                  setState(() => _selectedJadwal = value!);
                },
              ),
              const SizedBox(height: 16),
              if (_selectedJadwal == '1x sehari')
                _buildWaktuDropdown(
                  label: 'Waktu Makan',
                  value: _selectedWaktu1,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu1 = value!),
                ),
              if (_selectedJadwal == '2x sehari') ...[
                _buildWaktuDropdown(
                  label: 'Waktu Makan Pagi',
                  value: _selectedWaktu1,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu1 = value!),
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan Sore',
                  value: _selectedWaktu2,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu2 = value!),
                ),
              ],
              if (_selectedJadwal == '3x sehari') ...[
                _buildWaktuDropdown(
                  label: 'Waktu Makan Pagi',
                  value: _selectedWaktu1,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu1 = value!),
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan Siang',
                  value: _selectedWaktu2,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu2 = value!),
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan Sore',
                  value: _selectedWaktu3,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu3 = value!),
                ),
              ],
              if (_selectedJadwal == '4x sehari') ...[
                _buildWaktuDropdown(
                  label: 'Waktu Makan 1 (Pagi)',
                  value: _selectedWaktu1,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu1 = value!),
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan 2 (Siang)',
                  value: _selectedWaktu2,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu2 = value!),
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan 3 (Sore)',
                  value: _selectedWaktu3,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu3 = value!),
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan 4 (Malam)',
                  value: '18:00',
                  onChanged: (value) =>
                      setState(() => _selectedWaktu3 = value!),
                ),
              ],
              if (_selectedJadwal == 'Custom') ...[
                _buildWaktuDropdown(
                  label: 'Waktu Makan 1',
                  value: _selectedWaktu1,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu1 = value!),
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan 2 (Opsional)',
                  value: _selectedWaktu2,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu2 = value!),
                  isRequired: false,
                ),
                const SizedBox(height: 12),
                _buildWaktuDropdown(
                  label: 'Waktu Makan 3 (Opsional)',
                  value: _selectedWaktu3,
                  onChanged: (value) =>
                      setState(() => _selectedWaktu3 = value!),
                  isRequired: false,
                ),
                const SizedBox(height: 8),
                Text(
                  'Catatan: Untuk custom schedule, waktu akan disimpan dalam format "HH:MM, HH:MM"',
                  style: TextStyle(
                    fontSize: 12,
                    color: Colors.grey[600],
                    fontStyle: FontStyle.italic,
                  ),
                ),
              ],
              const SizedBox(height: 24),
              _buildSectionTitle('Status'),
              SwitchListTile(
                title: const Text('Binatang Aktif'),
                subtitle: const Text('Nonaktifkan jika binatang sakit/karantina'),
                value: _isActive,
                onChanged: _isLoading
                    ? null
                    : (value) => setState(() => _isActive = value),
                activeColor: Colors.green,
              ),
              const SizedBox(height: 32),
              _buildSubmitButton(),
              const SizedBox(height: 16),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Text(
        title,
        style: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w600,
          color: Colors.green,
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    String? hintText,
    List<String>? suggestions,
    String? Function(String?)? validator,
    int maxLines = 1,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontWeight: FontWeight.w500,
            fontSize: 14,
          ),
        ),
        const SizedBox(height: 6),
        TextFormField(
          controller: controller,
          decoration: InputDecoration(
            hintText: hintText,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            filled: true,
            fillColor: Colors.grey[50],
            suffixIcon: suggestions != null
                ? IconButton(
                    icon: const Icon(Icons.arrow_drop_down),
                    onPressed: () {
                      _showSuggestionsDialog(suggestions, controller);
                    },
                  )
                : null,
          ),
          validator: validator,
          maxLines: maxLines,
          minLines: maxLines == 1 ? 1 : null,
        ),
        const SizedBox(height: 16),
      ],
    );
  }

  Widget _buildDropdown({
    required String value,
    required String label,
    required List<String> items,
    required Function(String?) onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontWeight: FontWeight.w500,
            fontSize: 14,
          ),
        ),
        const SizedBox(height: 6),
        DropdownButtonFormField<String>(
          value: value,
          decoration: InputDecoration(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            filled: true,
            fillColor: Colors.grey[50],
          ),
          items: items.map((item) {
            return DropdownMenuItem<String>(
              value: item,
              child: Text(item),
            );
          }).toList(),
          onChanged: _isLoading ? null : onChanged,
          validator: (value) {
            if (value == null || value.isEmpty) {
              return 'Pilih frekuensi makan';
            }
            return null;
          },
        ),
      ],
    );
  }

  Widget _buildWaktuDropdown({
    required String label,
    required String value,
    required Function(String?) onChanged,
    bool isRequired = true,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontWeight: FontWeight.w500,
            fontSize: 14,
          ),
        ),
        const SizedBox(height: 6),
        DropdownButtonFormField<String>(
          value: value.isNotEmpty ? value : null,
          decoration: InputDecoration(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            filled: true,
            fillColor: Colors.grey[50],
          ),
          items: _waktuOptions.map((waktu) {
            return DropdownMenuItem<String>(
              value: waktu,
              child: Text(waktu),
            );
          }).toList(),
          onChanged: _isLoading ? null : onChanged,
          validator: isRequired
              ? (value) {
                  if (value == null || value.isEmpty) {
                    return 'Pilih waktu makan';
                  }
                  return null;
                }
              : null,
        ),
      ],
    );
  }

  Widget _buildSubmitButton() {
    return SizedBox(
      width: double.infinity,
      child: ElevatedButton(
        onPressed: _isLoading ? null : _tambahBinatang,
        style: ElevatedButton.styleFrom(
          backgroundColor: Colors.green,
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(vertical: 16),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
        child: _isLoading
            ? const SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  color: Colors.white,
                ),
              )
            : const Text(
                'Simpan Binatang',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
              ),
      ),
    );
  }

  void _showSuggestionsDialog(List<String> suggestions, TextEditingController controller) {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Pilih Spesies'),
          content: SizedBox(
            width: double.maxFinite,
            child: ListView.builder(
              shrinkWrap: true,
              itemCount: suggestions.length,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text(suggestions[index]),
                  onTap: () {
                    controller.text = suggestions[index];
                    Navigator.pop(context);
                  },
                );
              },
            ),
          ),
        );
      },
    );
  }
}