// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1xV4-YiyHcW9ex4kgM8LjaNTGBjbzWg',
    appId: '1:315538866870:web:e11477ced40937b6075c17',
    messagingSenderId: '315538866870',
    projectId: 'isisubuh-c7338',
    authDomain: 'isisubuh-c7338.firebaseapp.com',
    storageBucket: 'isisubuh-c7338.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03WdOtOlgbD0m8BPO3Nh6DUXPpH7Xn6c',
    appId: '1:315538866870:android:2f01d0af0a83580b075c17',
    messagingSenderId: '315538866870',
    projectId: 'isisubuh-c7338',
    storageBucket: 'isisubuh-c7338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY5EI26e-MnOYpfBeltJiYmUyFJc89C9o',
    appId: '1:315538866870:ios:dae108f09a723654075c17',
    messagingSenderId: '315538866870',
    projectId: 'isisubuh-c7338',
    storageBucket: 'isisubuh-c7338.firebasestorage.app',
    iosBundleId: 'com.example.zoofeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY5EI26e-MnOYpfBeltJiYmUyFJc89C9o',
    appId: '1:315538866870:ios:dae108f09a723654075c17',
    messagingSenderId: '315538866870',
    projectId: 'isisubuh-c7338',
    storageBucket: 'isisubuh-c7338.firebasestorage.app',
    iosBundleId: 'com.example.zoofeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG1xV4-YiyHcW9ex4kgM8LjaNTGBjbzWg',
    appId: '1:315538866870:web:785d57237ce7bb48075c17',
    messagingSenderId: '315538866870',
    projectId: 'isisubuh-c7338',
    authDomain: 'isisubuh-c7338.firebaseapp.com',
    storageBucket: 'isisubuh-c7338.firebasestorage.app',
  );
}
